# use the officilal Node.js image for the backend

FROM node:19-alpine

WORKDIR /use/src/app

# copy the package.json and package-lock.json files
COPY package*.json ./

RUN npm ci --only=production

COPY . .

# expose the port the app runs on
EXPOSE 5173

CMD ["node"]