version: '3.8'

services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: /.env
    # depends_on:
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/CoLabrium
      - JWT_SECRET=JWT123
      - BACKEND_URL=http://localhost:5000
